{% set name = "graphlib-backport" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/graphlib_backport-{{ version }}.tar.gz
  sha256: 7bb8fc7757b8ae4e6d8000a26cd49e9232aaa9a3aa57edb478474b8424bfaae2

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --use-deprecated=out-of-tree-build

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry
  run:
    - python >={{ python_min }},<4.0

test:
  imports:
    - graphlib
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/graphlib-backport/
  summary: Backport of the Python 3.9 graphlib module for Python 3.6+
  license: PSF-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
